[workspace]
members = [
    "crates/core",
    "crates/desktop",
    "crates/web"
]
default-members = ["crates/desktop"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
strip = "debuginfo"

[workspace.dependencies]
bevy = "0.15.3"
bevy-midi-graph = { git = "https://github.com/grimace87/bevy-midi-graph.git", rev = "1d79dc3343ac6ff2aa6b1c558b61d91ea60e46e0" }

